<a href="https://colab.research.google.com/github/stefanny84/CP2---SERS/blob/main/CP2_SERS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1CCA

Letícia Gabrielle Andrade Temoteo, 563985

Stefanny Brum dos Santos, 566216

# Exercício 1 – Classificação (Solar)
Previsão de nível de radiação solar
Dataset sugerido: Solar Radiation Prediction Dataset – Kaggle
(https://www.kaggle.com/datasets/dronio/SolarEnergy)

In [ ]:
''' Utilize o dataset de radiação solar para treinar um modelo supervisionado para classificar
períodos em Alta Radiação e Baixa Radiação (crie a variável-alvo a partir de um limiar,
por exemplo, a mediana da radiação). Compare o desempenho de três algoritmos do
Scikit-learn, como Árvore de Decisão, Random Forest e Support Vector Machine
(SVM). '''

In [ ]:
import pandas as pd

df = pd.read_csv("SolarPrediction.csv")
threshold = df["Radiation"].median()
df["target"] = (df["Radiation"] >= threshold).astype(int)


In [ ]:
# Separe dados em treino e teste (70/30)

import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv("SolarPrediction.csv")

threshold = df["Radiation"].median()
df["target"] = (df["Radiation"] >= threshold).astype(int)

X = df.drop(columns=["Radiation", "target", "Data", "Time", "TimeSunRise", "TimeSunSet"])
y = df["target"]

# Separar treino e teste (70/30)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

display(X_train.head())
display(X_test.head())
display(y_train.head())
display(y_test.head())

UNIXTime  Temperature  Pressure  Humidity  WindDirection(Degrees)  \
3446   1474168208           58     30.45        77                   95.83   
32031  1480782634           45     30.31        93                  174.86   
21155  1479005702           56     30.44        88                   54.45   
17759  1480025403           50     30.47        97                   30.95   
27051  1482504649           44     30.43        42                  135.58   

       Speed  
3446    3.37  
32031  11.25  
21155   1.12  
17759  13.50  
27051  12.37

UNIXTime  Temperature  Pressure  Humidity  WindDirection(Degrees)  \
15870  1475428528           51     30.45       100                  158.85   
12232  1476542724           50     30.46        23                  178.09   
6415   1473042602           55     30.44       101                   35.42   
5104   1473586819           47     30.43        93                  213.40   
19067  1479632420           50     30.46       100                   92.66   

       Speed  
15870   4.50  
12232   7.87  
6415    3.37  
5104    2.25  
19067   5.62

3446     1
32031    0
21155    1
17759    1
27051    0
Name: target, dtype: int64

15870    1
12232    0
6415     1
5104     0
19067    0
Name: target, dtype: int64

In [ ]:
# Normalize os atributos contínuos, se necessário.

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

# Inicializar modelos
models = {
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "SVM": SVC(random_state=42)
}

# Treinar
for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    print(f"{name} treinado com sucesso!")


Decision Tree treinado com sucesso!
Random Forest treinado com sucesso!
SVM treinado com sucesso!


In [ ]:
# Avalie com acurácia e matriz de confusão.
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

for name, model in models.items():
    y_pred = model.predict(X_test_scaled)
    acc = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)

    print(f"\n{name}")
    print("Acurácia:", round(acc, 3))
    print("Matriz de Confusão:\n", cm)
    print("Relatório de Classificação:\n", classification_report(y_test, y_pred))


Decision Tree
Acurácia: 0.943
Matriz de Confusão:
 [[4631  272]
 [ 284 4619]]
Relatório de Classificação:
               precision    recall  f1-score   support

           0       0.94      0.94      0.94      4903
           1       0.94      0.94      0.94      4903

    accuracy                           0.94      9806
   macro avg       0.94      0.94      0.94      9806
weighted avg       0.94      0.94      0.94      9806


Random Forest
Acurácia: 0.944
Matriz de Confusão:
 [[4741  162]
 [ 389 4514]]
Relatório de Classificação:
               precision    recall  f1-score   support

           0       0.92      0.97      0.95      4903
           1       0.97      0.92      0.94      4903

    accuracy                           0.94      9806
   macro avg       0.94      0.94      0.94      9806
weighted avg       0.94      0.94      0.94      9806


SVM
Acurácia: 0.849
Matriz de Confusão:
 [[4653  250]
 [1226 3677]]
Relatório de Classificação:
               precision    recal

# **Exercício 2 – Regressão (Eólica)**
 Previsão de potência de turbinas eólicas
 Dataset sugerido: Wind Turbine Scada Dataset – Kaggle
(https://www.kaggle.com/datasets/berkerisen/wind-turbine-scada-dataset)


In [ ]:
''' Com base nos dados de operação de turbinas eólicas (velocidade do vento, ângulo do
rotor, densidade do ar, etc.), treine modelos de regressão para prever a potência gerada
(kW). Compare o desempenho de três algoritmos do Scikit-learn, como Regressão
Linear, Regressão de Árvores e Random Forest Regressor. '''

In [ ]:
# Separe treino e teste (80/20).

df = pd.read_csv("T1.csv")
y = df["LV ActivePower (kW)"]
X = df.drop(columns=["LV ActivePower (kW)", "Date/Time"])

# Separar treino e teste (80/20)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

display(X_train.head())
display(X_test.head())
display(y_train.head())
display(y_test.head())

Wind Speed (m/s)  Theoretical_Power_Curve (KWh)  Wind Direction (°)
13791          2.799033                       0.000000          179.881195
46267          4.963243                     327.020704          123.176598
42105         12.740750                    3592.761778          211.334000
21123          7.094672                    1059.182279           54.425968
11823          6.279566                     722.431353           42.774040

Wind Speed (m/s)  Theoretical_Power_Curve (KWh)  Wind Direction (°)
8057          11.632760                    3452.918718          188.499802
8059          10.345970                    2989.120313          190.715607
50250          6.430618                     779.117347           29.279140
14774          7.952174                    1502.728868           49.509399
49374          5.906481                     593.890170          278.626190

13791       0.000000
46267     292.170105
42105    3387.934082
21123    1082.370972
11823     550.262329
Name: LV ActivePower (kW), dtype: float64

8057     3348.910889
8059     2647.506104
50250       0.000000
14774    1334.573975
49374     533.002808
Name: LV ActivePower (kW), dtype: float64

In [ ]:
# Normalize os dados, se necessário.

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

models = {
    "Regressão Linear": LinearRegression(),
    "Árvore de Regressão": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(random_state=42)
}

# Treinar
for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    print(f"{name} treinado com sucesso!")

Regressão Linear treinado com sucesso!
Árvore de Regressão treinado com sucesso!
Random Forest treinado com sucesso!


In [ ]:
for name, model in models.items():
    y_pred = model.predict(X_test_scaled)

    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)

    print(f"\n{name}")
    print("RMSE:", round(rmse, 2))
    print("R²:", round(r2, 3))


Regressão Linear
RMSE: 411.71
R²: 0.901

Árvore de Regressão
RMSE: 538.79
R²: 0.83

Random Forest
RMSE: 412.82
R²: 0.9
